### ISSUE TITLE
Google Play

### ISSUE THREAD

**Issue by achimwagenknecht** [jmyrland/DriSMo#2]
Hi,

I really love DriSMo, thank you very much for this great App! But I can't find it on Google Play. Can you upload it?

Kind regards
Achim

**Comment by jmyrland** [comment]
Thank you 🙂 Google removed it because the app was not updated. But I can link you the APK file so you can install it on your own: https://www.dropbox.com/s/reglku8dlht7nxt/DriSMo3.apk?dl=0

**Comment by achimwagenknecht** [comment]
Thank you very much!
